// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type {
    Metadata,
    ResolvingMetadata,
    ResolvingViewport,
    Viewport,
} from 'next/types.js'
import type { ComponentType, ReactNode } from 'react'
import type { AppRoutes, LayoutRoutes, ParamMap } from './routes.js'

type AppPageProps<Route extends AppRoutes> = {
    params: Promise<ParamMap[Route]>
} & Record<string, unknown>

type LayoutGeneratorProps<Route extends LayoutRoutes> = {
    params: Promise<ParamMap[Route]>
} & Record<string, unknown>

type StaticParamsResult = ReadonlyArray<Record<string, unknown>>

type MetadataResult = Metadata | null | undefined
type ViewportResult = Viewport | null | undefined

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
    default:
        | ComponentType<AppPageProps<Route>>
        | ((
              props: AppPageProps<Route>
          ) => ReactNode | Promise<ReactNode> | never | void | Promise<void>)
    generateStaticParams?: (props: {
        params: ParamMap[Route]
    }) => StaticParamsResult | Promise<StaticParamsResult>
    generateMetadata?: (
        props: AppPageProps<Route>,
        parent: ResolvingMetadata
    ) => MetadataResult | Promise<MetadataResult>
    generateViewport?: (
        props: AppPageProps<Route>,
        parent: ResolvingViewport
    ) => ViewportResult | Promise<ViewportResult>
    metadata?: Metadata
    viewport?: Viewport
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
    default:
        | ComponentType<LayoutProps<Route>>
        | ((
              props: LayoutProps<Route>
          ) => ReactNode | Promise<ReactNode> | never | void | Promise<void>)
    generateStaticParams?: (props: {
        params: ParamMap[Route]
    }) => StaticParamsResult | Promise<StaticParamsResult>
    generateMetadata?: (
        props: LayoutGeneratorProps<Route>,
        parent: ResolvingMetadata
    ) => MetadataResult | Promise<MetadataResult>
    generateViewport?: (
        props: LayoutGeneratorProps<Route>,
        parent: ResolvingViewport
    ) => ViewportResult | Promise<ViewportResult>
    metadata?: Metadata
    viewport?: Viewport
}

// Validate ../../src/app/page.tsx
{
    type __IsExpected<Specific extends AppPageConfig<'/'>> = Specific
    type _Check = __IsExpected<typeof import('../src/app/page.tsx')>
    void (null as unknown as _Check)
}

// Validate ../src/app/layout.tsx
{
    type __IsExpected<Specific extends LayoutConfig<'/'>> = Specific
    type _Check = __IsExpected<typeof import('../src/app/layout.js')>
    void (null as unknown as _Check)
}
